<?php


/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/


$fibonacciArr = [1, 2];
$total = 0;

do {
    $length = count($fibonacciArr);
    array_push($fibonacciArr, ($fibonacciArr[$length - 1] + $fibonacciArr[$length - 2]));
} while ($fibonacciArr[count($fibonacciArr) - 1] + $fibonacciArr[count($fibonacciArr) - 2] < 4000000);

array_walk($fibonacciArr, function ($value) use (&$total) {
    if ($value % 2 === 0) {
        $total += $value;
    }
});

echo $total;